apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nginx-proxy-manager
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
        tier: frontend
    spec:
      containers:
      - name: nginx-alpine
        image: nginx:alpine
        ports:
        - name: port-811
          containerPort: 81
        - name: port-80
          containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html"
          name: alpine-storage
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: pvc-npm