apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nginx-proxy-manager
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
        tier: frontend
    spec:
      containers:
      - name: nginx-proxy-manager
        image: jc21/nginx-proxy-manager:latest
        ports:
        - name: port-81
          containerPort: 81
        - name: port-80
          containerPort: 80
        volumeMounts:
        - mountPath: "/data"
          name: nginx-data-storage
        - mountPath: "/var/www/html"
          name: nginx-config-storage
      volumes:
      - name: nginx-data-storage
        persistentVolumeClaim:
          claimName: pvc-data
      - name: nginx-config-storage
        persistentVolumeClaim:
          claimName: pvc-npm


