apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-data-persistent-volume
  labels:
    app: nginx-proxy-manager
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/project/lat/NPM/nginx"