apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi