apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager-services
  labels:
    app: nginx-proxy-manager
spec:
  ports:
  - name: port-81
    port: 81
    targetPort: 81
  - name: port-5000
    port: 5000
    targetPort: 80
  externalIPs:
    - x.x.x.x
  selector:
    app: nginx-proxy-manager
    tier: frontend
  type: NodePort