apiVersion: v1
kind: Service
metadata:
  name: nginx-mysql
  labels:
    app: nginx-proxy-manager
spec:
  ports:
    - port: 3306
  selector:
    app: nginx-proxy-manager
    tier: mysql
  clusterIP: None